CREATE TABLE `monitors` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`resolution` varchar(100) NOT NULL,
	`panelType` varchar(100) NOT NULL,
	`refreshRate` varchar(100) NOT NULL,
	`brightness` varchar(100) NOT NULL,
	`contrast` varchar(100) NOT NULL,
	`responseTime` varchar(100) NOT NULL,
	`connectivity` varchar(255) NOT NULL,
	`size` varchar(50) NOT NULL,
	`condition` varchar(50) NOT NULL,
	`warranty` varchar(100) NOT NULL,
	`price` int NOT NULL,
	`imageUrl` text,
	`description` text,
	`category` enum('promotions','refurbished','new','gaming','professional','budget') NOT NULL DEFAULT 'new',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `monitors_id` PRIMARY KEY(`id`)
);
